freedomotic/fd-vue-webapp

- package-lock.json
- package.json
- src/main.js
> Add vue-axios support

- .travis.yml
I have add config to travisCI in PR.
> Add travisCI config initial.

- package-lock.json
- package.json
- src/App.vue
- src/auth/auth.js
- src/components/AppInfo.vue
- src/components/Background.vue
- src/components/Bugs.vue
- src/components/Dashboard.vue
- src/components/InfoBox.vue
- src/components/Login.vue
- src/components/Logout.vue
- src/components/Settings.vue
- src/main.js
- test/e2e/specs/test.js
This PR adds a series of improvements to the current prototype GUI.
Basically this introduces:
- Logout component
- Background component
- Settings component
- a series of accessory components as "Bugs", "InfoBox".
So far the Travis CI fails, however this failure is not due to added source code. Instead, it seems to depend on npm versions issues that I am going to address in next hours.
> Graphical improvements

- package-lock.json
- src/components/Dashboard.vue
- src/components/InfoBox.vue
- src/main.js
- src/store/actions.js
- src/store/index.js
- src/store/mutations.js
This PR contains a first working scaffolding support for Vuex.
From now, please try to implement state management and event messages across components using respectively Vuex mutations and actions.
> Vuex, first scaffolding set up

- src/components/Background.vue
- src/components/BottomMenu.vue
This PR adds a botton button in the background component for support of bottom menu section.
> Bottom Menu component scaffolding

- src/components/AppInfo.vue
- src/components/Login.vue
- src/components/Logout.vue
- src/components/Plugin.vue
- src/i18n/en.json
- src/i18n/it_IT.json
Other strings added to translations
> Updated i18n strings in some components

- src/components/AppInfo.vue
- src/components/Logout.vue
- src/components/Settings.vue
This PR should **hopefully** fix the problem about background rendering of some components.
> graphical issue solved

- package-lock.json
- package.json
- src/components/LanguagesPanel.vue
Flags representing available languages added.
> issue 62 fixed

- src/components/Environment.vue
- src/components/EnvironmentsPanel.vue
This fix aligns the environment in the center of the screen using CSS Flex Box layout.
Moreover, it performs a proper centering of the enviroment image background in the canvas.
> issue 87 solved with proper alignment

- src/components/Thing.vue
- src/components/ThingsPanel.vue
This PR fixes the grid layout of Things panel.
> issue 71, things panel properly aligned

- src/components/InfoBox.vue
- src/components/Settings.vue
The source code of this PR provides a proper realignment of `Settings.vue` layout in order to make it leaner.
> settings panel proper realignment

- src/components/CloseButton.vue
- src/components/InfoBox.vue
This solves #56 by overriding original CSS classes.
> Issue 56 - Fixed by introduction of proper CSS selectors

- package-lock.json
- package.json
- src/components/Environment.vue
this fixes #163.
Please note that I removed `v-tooltip` as dependency because a tooltip component is already existing in `vue-material`.
Generally it'd be better to stay with a lower number of dependencies.
> Fixing tooltip layout for things.

- package-lock.json
- src/components/ThingsEditor.vue
This fixes issue #179 
The pull request refactors ThingsEditor to use md-tabs instead of vue-tabs.
> Changes ThingsEditor to use md-tabs instead of vue-tabs

- src/components/Environment.vue
Added TopNav unit and Display Unit.
Touched up styling to scale and center correctly.
> Refactor Environment Component

- src/store/getters.js
- src/store/index.js
Add a vuex getter to return triggers from the triggersList where hardwareLevel is true
Getter in action:
> Closes #94

- src/components/Environment.vue
> Set environment background image from api

- src/store/getters.js
> add new getter for protocols

- src/components/Environment.vue
> things context menu in enviroment component opens a dialog

- src/components/Login.vue
> Add background to login

- src/components/AddThingDialog.vue
- src/components/ThingsPanel.vue
> Add a button and a dialog shell for adding new thing
